# Generated by Django 4.1.5 on 2023-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todolistitem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='content',
            field=models.CharField(help_text='Введите название задачи', max_length=99),
        ),
    ]
